[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning
    ignore:.*Using `httpx` with `starlette.testclient` is deprecated.*:Warning
    ignore:.*StarletteDeprecationWarning.*
    ignore:.*BlockingPortal.*
    ignore::Warning:fastapi.testclient
